const STEAMSPREADSHEETID = "1HuE5IQVVjHGUkPOCiSvNAC0hFGe48HFl0lcDsNa2bXU";
const COMMUNICATIONDOCID = "1yg-prfPzWtPNCuODujn8Ch2_8lW-REp1lTBmZ9BIMo8";
const ROSTERDOCID = "1_4-cqzbVj37tMTbOloqyHs5cYfjpp21zkTWQTRcXjJo";
const TABLEDOCID = "13-uivd6IA7_VXX5D6S0j0Ms6yors2E2nzYvMYyw2io8";
const TEACHERDOCID = "188XWcPbZDT82W2mkfsAvGr_QBI6LvP-omYq13i18t7o";
const HEADERIMAGEID = "1g0FYbnhaGlGk0lvqx_nJet0xk3oQ35Jr"

const STUDENTNAME = 0;
const STUDENTID = 1;
const STUDENTPHONE = 2;
const STUDENTGRADE = 3;
const STUDENTCLASS = 4;
const STUDENTSESSION1 = 5;
const STUDENTSESSION2 = 6;

const SESSIONID = 0;
const SESSIONNAME = 1;
const SESSIONTEACHER = 2;
const SESSIONLOCATION = 3;
const SESSIONDATES = 4;

const HEADERWIDTH = 300;
const COLUMNWIDTH = 180;
const DATEFORMAT = "MMM d";
const DATEFORMATNUMBER = "M/d";

const SESSIONSRANGE = "Sessions!A2:K";
const STUDENTSRANGE = "Students!A2:G";
